# Generated by Django 6.0.4 on 2026-04-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
