# Generated by Django 6.0.4 on 2026-05-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_created_at_post_udated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Posts', 'verbose_name_plural': 'Post'},
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, null=True),
        ),
    ]
